В этом задании вы познакомитесь с методом подсчета косинусного расстояния. Задача — найти два предложения, которые ближе всего по смыслу к расположенному в самой первой строке. В качестве меры близости по смыслу мы будем использовать косинусное расстояние.

In [1]:
import numpy as np
import scipy.spatial
import re
from itertools import chain

In [15]:
with open('text_for_w2.txt', 'r') as file_obj:
    sentences = [line.strip().lower() for line in file_obj]
# .strip() Возвращает копию указанной строки, с обоих концов которой устранены указанные символы.

Производим токенизацию, то есть разбиение текстов на слова. Для этого можно воспользоваться регулярным выражением, которое считает разделителем любой символ, не являющийся буквой: re.split('[^a-z]', t).

In [13]:
regexp = re.compile('[^a-z]') # Компилим регулярное выражение
print(re.split(regexp ,sentences[0]))
sentence = [[word for word in re.split(regexp, line) if word] for line in sentences]

['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '']


Генерируем словарь слов из листа присваивая им индексы

In [16]:
# Из ряда итерируемых делает один итерируемый (конкатенация листов например)
words = {word: index for index, word in enumerate(set(chain(*sentence)))}
word = {word: index for index, word in enumerate(["hello", "world"])}
print(len(words))

254


Создаем матрицу размера n * d, где n — число предложений. 

In [8]:
matrix = np.zeros((len(sentences), len(words)))
matrix.shape

(22, 254)

In [17]:
for i in range(len(sentences)): # Заполняем матрицу
    for j in sentence[i]:
        matrix[i][words[j]] += 1
print(matrix)

[[2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 4. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Косинусная близость - косинус угла между 2 векторами

In [10]:
distances = [(index, scipy.spatial.distance.cosine(matrix[0], matrix[index])) for index in range(len(sentences))]
print(distances)
sorted_distance = sorted(distances, key=lambda x: x[1])
print(sorted_distance[1][0], sorted_distance[2][0])

[(0, 0.0), (1, 0.9527544408738466), (2, 0.8644738145642124), (3, 0.8951715163278082), (4, 0.7770887149698589), (5, 0.9402385695332803), (6, 0.7327387580875756), (7, 0.9258750683338899), (8, 0.8842724875284311), (9, 0.9055088817476932), (10, 0.8328165362273942), (11, 0.8804771390665607), (12, 0.8396432548525454), (13, 0.8703592552895671), (14, 0.8740118423302576), (15, 0.9442721787424647), (16, 0.8406361854220809), (17, 0.956644501523794), (18, 0.9442721787424647), (19, 0.8885443574849294), (20, 0.8427572744917122), (21, 0.8250364469440588)]
6 4


In [12]:
print(sorted_distance[1:3])

[(6, 0.7327387580875756), (4, 0.7770887149698589)]


In [11]:
print(sentences[sorted_distance[1][0]])
print(sentences[sorted_distance[2][0]])

domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).
in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.
